export const PlayerActionTypes = {
    REGISTER_PLAYER_START: 'REGISTER_PLAYER_START',
    REGISTER_PLAYER_SUCCESS: 'REGISTER_PLAYER_SUCCESS',
    REGISTER_PLAYER_FAILURE: 'REGISTER_PLAYER_FAILURE',
    FETCH_PLAYER_PRIMARY_PROFILE_START: 'FETCH_PLAYER_PRIMARY_PROFILE_START',
    FETCH_PLAYER_PRIMARY_PROFILE_SUCCESS: 'FETCH_PLAYER_PRIMARY_PROFILE_SUCCESS',
    FETCH_PLAYER_PRIMARY_PROFILE_FAILURE: 'FETCH_PLAYER_PRIMARY_PROFILE_FAILURE',
    UPDATE_PLAYER_PRIMARY_PROFILE_START: 'UPDATE_PLAYER_PRIMARY_PROFILE_START',
    UPDATE_PLAYER_PRIMARY_PROFILE_SUCCESS: 'UPDATE_PLAYER_PRIMARY_PROFILE_SUCCESS',
    UPDATE_PLAYER_PRIMARY_PROFILE_FAILURE: 'UPDATE_PLAYER_PRIMARY_PROFILE_FAILURE',
    CLEAR_PLAYER_PRIMARY_PROFILE: 'CLEAR_PLAYER_PRIMARY_PROFILE'
}